// generated by Fast Light User Interface Designer (fluid) version 1.00

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/fl_ask.H>

#include <Flek/Fl_Input_File.H>
#include <Flek/Fl_File_Dialog.H>

Fl_Button *exit_button=(Fl_Button *)0;
Fl_Input_File  *file_input =(Fl_Input_File *)0;
char selection[FL_MAX_PATH+200];  //place selection into this array
int slash;                        //where slash starts

//|
//|  Exit program
//|
void exit_cb(Fl_Widget *, void *v) {
   if(slash) fl_message((char*)(selection+slash));
   exit(0);
}

//|
//|  load Input_File with selection from FileDialog
//|
void select_cb(Fl_Widget *, void *v) {
   slash = fl_file_dialog("Open File",selection,0,0,0);
   file_input->setFilename(selection); 
}

//|
//|  Main demo program for file_dialog widget
//|
int main(int argc, char **argv) {
  Fl_Window* w;
  strcpy(selection, "*.*"); 
  { Fl_Window* o = new Fl_Window(415, 163);
    w = o;
    { Fl_Box* o = new Fl_Box(5, 5, 405, 25, "File Dialog / Input File");
      o->box(FL_DOWN_BOX);
      o->color(51);
      o->labelfont(1);
      o->labelsize(17);
    }
    { Fl_Button* o = exit_button = new Fl_Button(148, 131, 122, 25, "Exit");
      o->callback((Fl_Callback*)exit_cb);
    }
    { Fl_Input_File* o = file_input = new Fl_Input_File(8, 50, 398, 35, "File input:", selection);
      o->labelfont(1);
      o->labelsize(12);
      o->textsize(12);
      o->align(1);
      o->setFilename(selection); 
    }
    { Fl_Button* o = new Fl_Button(10, 89, 396, 19, "Select Directory");
      o->box(FL_THIN_UP_BOX);
      o->color(48);
      o->labelsize(10);
      o->labelcolor(1);
      o->callback((Fl_Callback*)select_cb);
    }
    o->end();
  }
  w->show(argc, argv);
  return Fl::run();
}
