# Documentation Makefile

all:

docs:
	perl scandoc.pl -itemplate.pl -t4 ../Flek/*.h \
	../Flek/Fl_App_Window.H \
	../Flek/Fl_Stock.H \
	../Flek/Fl_Toggle_Tree.H \
	../Flek/Fl_Toggle_Tree_Base.H \
	../Flek/Fl_Gl_Arcball_Window.H \
	../Flek/Fl_Dockable_Group.H \
	../Flek/Fl_Calendar.H


install:

clean:

# uncomment this line when the documentation transition is complete!!
# rm *.html

distclean: clean

depend:
